var info=[
    {
        name:"sajid",
        roll:01,
        age:28,
        subject:["english","bangla","math","biology"],
        friends:[
            {
                name:"sujon",
                roll:23,
                age:27,
                subject:["english","bangla","math","biology"],
                friends:[
                    name:"saddam",
                    roll:45,
                    age:29,
                    subject:["english","bangla","math","biology"],
                ]
            },
            {
                name:"sujon",
                roll:23,
                age:27,
                subject:["english","bangla","math","biology"],
                friends:[
                    name:"saddam",
                    roll:45,
                    age:29,
                    subject:["english","bangla","math","biology"],
                ]
            }
        ]
    },
    {
        name:"shohan",
        roll:01,
        age:28,
        subject:["english","bangla","math","biology"],
        friends:[
            {
                name:"ajad",
                roll:3653,
                age:28632322378,
                subject:["english","bangla","math","biology"],
                address:"sherpur","bangladesh"
            }
        ]
    },
    {
        name:"jihan",
        roll:527232781,
        age:289208397,
        subject:["english","bangla","math","biology"],
    },
    {
        name:"siam",
        roll:07149871,
        age:26117118755358,
        subject:["english","bangla","math","biology"],
    }
];
console.log(info.length);

